apiVersion: v1
kind: ResourceQuota
metadata:
  name: stage-quota
  namespace: stage
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 6Gi
    limits.cpu: "6"
    limits.memory: 12Gi
    pods: "30"
