apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev 

resources:
  - ../../base

images:
  - name: adservice
    newName: docker.io/gcrio/google-samples/microservices-demo/adservice
    newTag: v0.10.0
  - name: cartservice
    newName: docker.io/gcrio/google-samples/microservices-demo/cartservice
    newTag: v0.10.0
  - name: checkoutservice
    newName: docker.io/gcrio/google-samples/microservices-demo/checkoutservice
    newTag: v0.10.0
  - name: currencyservice
    newName: docker.io/gcrio/google-samples/microservices-demo/currencyservice
    newTag: v0.10.0
  - name: emailservice
    newName: docker.io/gcrio/google-samples/microservices-demo/emailservice
    newTag: v0.10.0
  - name: frontend
    newName: docker.io/gcrio/google-samples/microservices-demo/frontend
    newTag: v0.10.0
  - name: paymentservice
    newName: docker.io/gcrio/google-samples/microservices-demo/paymentservice
    newTag: v0.10.0
  - name: productcatalogservice
    newName: docker.io/gcrio/google-samples/microservices-demo/productcatalogservice
    newTag: v0.10.0
  - name: recommendationservice
    newName: docker.io/gcrio/google-samples/microservices-demo/recommendationservice
    newTag: v0.10.0
  - name: shippingservice
    newName: docker.io/gcrio/google-samples/microservices-demo/shippingservice
    newTag: v0.10.0